export const YandexMapPreset2LineId = [
	{ YandexMapPresetName: 'islands#redIcon', lineId: '1' },
	{ YandexMapPresetName: 'islands#darkGreenIcon', lineId: '2' },
	{ YandexMapPresetName: 'islands#darkBlueIcon', lineId: '3' },
	{ YandexMapPresetName: 'islands#blueIcon', lineId: '4' },
	{ YandexMapPresetName: 'islands#brownIcon', lineId: '5' },
	{ YandexMapPresetName: 'islands#darkOrangeIcon', lineId: '6' },
	{ YandexMapPresetName: 'islands#violetIcon', lineId: '7' },
	{ YandexMapPresetName: 'islands#yellowIcon', lineId: '8' },
	{ YandexMapPresetName: 'islands#grayIcon', lineId: '9' },
	{ YandexMapPresetName: 'islands#greenIcon', lineId: '10' },
	{ YandexMapPresetName: 'islands#lightBlueIcon', lineId: '11' },
	{ YandexMapPresetName: 'islands#lightBlueIcon', lineId: '12' },
	{ YandexMapPresetName: 'islands#yellowIcon', lineId: '133' },
	{ YandexMapPresetName: 'islands#pinkDotIcon', lineId: '95' },
	{ YandexMapPresetName: 'islands#darkBlueDotIcon', lineId: '96' },
	{ YandexMapPresetName: 'islands#lightBlueIcon', lineId: '97' },
	{ YandexMapPresetName: 'islands#pinkIcon', lineId: '98' },
	{ YandexMapPresetName: 'islands#darkOrangeDotIcon', lineId: '131' },
	{ YandexMapPresetName: 'islands#violetDotIcon', lineId: '132' },
	{ YandexMapPresetName: 'islands#redDotIcon', lineId: '135' },
	{ YandexMapPresetName: 'islands#darkGreenDotIcon', lineId: '136' },
];
